import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

// ─── Signing config ──────────────────────────────────────────────────────────
//
// We sign BOTH debug AND release builds with the same persistent keystore so
// that downstream installs can be updated in place (Android refuses to update
// an installed app when the new APK is signed by a different key — the cause
// of "приложение не установлено" we hit earlier).
//
// Keystore source priority:
//   1. Env vars (CI):   ANDROID_KEYSTORE_BASE64 / _PASSWORD / _ALIAS / _KEY_PASSWORD
//   2. local.properties (developer machine): keystorePath / keystorePassword /
//      keyAlias / keyPassword
//   3. Fallback: standard ~/.android/debug.keystore (regenerated by AGP if
//      missing — useful for first-time local setup, but signature differs
//      between machines)
//
// In CI the workflow base64-decodes ANDROID_KEYSTORE_BASE64 to a file before
// gradle runs, then sets KEYSTORE_PATH to point at that file.

val localProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}

fun secret(envKey: String, propKey: String): String? =
    System.getenv(envKey) ?: localProps.getProperty(propKey)

// Names below are intentionally NOT `keyAlias` / `keyPassword` — those names
// shadow SigningConfig.keyAlias / keyPassword inside the create("wispr") DSL
// closure, causing self-assignment to null. Use prefixed names that don't
// collide with the receiver's property names.
val ksPath = secret("KEYSTORE_PATH", "keystorePath")
val ksPassword = secret("ANDROID_KEYSTORE_PASSWORD", "keystorePassword")
val ksAlias = secret("ANDROID_KEY_ALIAS", "keyAlias")
// Convention: keystore and key passwords are usually identical (keytool offers
// "press Enter to use store password"). If ANDROID_KEY_PASSWORD isn't set,
// fall back to ANDROID_KEYSTORE_PASSWORD instead of failing the build.
val ksKeyPassword = secret("ANDROID_KEY_PASSWORD", "keyPassword")
    ?.takeIf { it.isNotBlank() }
    ?: ksPassword
val haveCustomKeystore = listOf(ksPath, ksPassword, ksAlias, ksKeyPassword)
    .all { !it.isNullOrBlank() }

android {
    namespace = "com.wispralt.keyboard"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.wispralt.keyboard"
        minSdk = 26
        targetSdk = 34
        versionCode = 10
        versionName = "0.7.1"

        // Backend URL baked in at compile time.
        val backendUrl = System.getenv("WISPR_BACKEND_URL")
            ?: "https://alrcvscribe.n8nrgimprovise.space"
        buildConfigField("String", "BACKEND_URL", "\"$backendUrl\"")
    }

    signingConfigs {
        if (haveCustomKeystore) {
            create("wispr") {
                storeFile = file(ksPath!!)
                storePassword = ksPassword
                keyAlias = ksAlias
                keyPassword = ksKeyPassword
            }
        }
    }

    buildTypes {
        debug {
            if (haveCustomKeystore) {
                signingConfig = signingConfigs.getByName("wispr")
            }
        }
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            if (haveCustomKeystore) {
                signingConfig = signingConfigs.getByName("wispr")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    // HTTP client for backend calls
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    // Coroutines for async work
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
}
